version: '2.4'
services:
  cassandra:
    image: cassandra:3.11.9
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra", "-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - ${BASE_PATH}/docker/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml
  cassandra-sidecar:
    container_name: cassandra-sidecar
    image: cassandra:3.11.9
    depends_on:
      - cassandra
    restart: on-failure
    volumes:
      - ${BASE_PATH}/docker/cassandra/configure-db.cql:/configure-db.cql
    command: /bin/bash -c "cqlsh cassandra -f /configure-db.cql"
networks:
  default:
    external:
      name: demo